resources:
  - namespace.yaml
  - prometheus-configmap.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - sonarqube-deployment.yaml
  - sonarqube-service.yaml
